name: Dependabot Auto Merge
description: Automatically merge Dependabot PRs when version comparison is within range

branding:
  color: blue
  icon: git-merge

inputs:
  min-approvals:
    description: number of approvals required
    required: true

  github-token:
    description: The GitHub token used to approve the pull-request
    required: true

  github-token1:
    description: The GitHub token used to approve and then merge the pull-request
    required: true

  github-token-user:
    description: The GitHub username for the first token
    required: true

  github-token1-user:
    description: The GitHub username for the second token
    required: true

  heroku-token:
    description: The Heroku token for accessing Heroku API
    required: true

  heroku-release-app:
    description: The Heroku app name for checking if any release is happening
    required: true

  target:
    description: The version comparison target (major, minor, patch). This is ignored if .github/auto-merge.yml exists
    default: patch
    required: false

runs:
  using: docker
  image: Dockerfile
